spring:
  application:
    name: sportyper
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/sportyper?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: sportyper
    password: sportyper2017
    validation-query: SELECT 1
    test-on-borrow: true
    test-on-return: true
  jackson:
    mapper:
      default-view-inclusion: true

server:
  port: 3000

management:
  port: 3001